Feat yolov5 segmenter
jina-ai/executor-yolov5 pull request #1
Opened 2021-07-21 10:55 UTC by alaeddine-13

closes https://github.com/jina-ai/internal-tasks/issues/118

2021-07-21 11:00 UTC, JoanFM commented on tests/integration/test_exec.py
> +            assert chunk.tags.get("label")
single quote

2021-07-21 11:00 UTC, JoanFM commented on yolov5_segmenter.py
> +                 default_confidence_threshold: float = 0.25,
I would expect a higher default?

2021-07-21 11:28 UTC, alaeddine-13 commented on yolov5_segmenter.py
> +                 default_confidence_threshold: float = 0.25,
something like 0.5 ?

2021-07-21 11:32 UTC, tadejsv commented on README.md
> +- [YoloV5 paper](https://arxiv.org/abs/1506.02640v5)
This is v5 of the (original) YOLO paper, it is not a paper of YOLOv5. It's an important distinction.

2021-07-21 11:34 UTC, tadejsv commented on yolov5_segmenter.py
> +            self.logger.error('Torch device not supported. Must be cpu or cuda!')
Not sure this is a good idea... In this case, `cuda:0` or `cuda:1` will not be accepted, yet they are valid pytorch device names.

2021-07-21 11:39 UTC, alaeddine-13 commented on README.md
> +- [YoloV5 paper](https://arxiv.org/abs/1506.02640v5)
so I'll make it just YoloV paper

2021-07-21 11:42 UTC, tadejsv commented on README.md
> +- [YoloV5 paper](https://arxiv.org/abs/1506.02640v5)
Just YOLO (v refers to version)

2021-07-21 12:01 UTC, alaeddine-13 commented on README.md
> +- [YoloV5 paper](https://arxiv.org/abs/1506.02640v5)
Yeah sorry it was a typo

2021-07-21 12:32 UTC, JoanFM commented on yolov5_segmenter.py
> +                 default_confidence_threshold: float = 0.25,
I would go more like 0.9

2021-07-21 13:02 UTC, alaeddine-13 commented on yolov5_segmenter.py
> +            self.logger.error('Torch device not supported. Must be cpu or cuda!')
fixed

2021-07-21 15:37 UTC, cristianmtr submitted a review, later dismissed

2021-07-21 15:37 UTC, cristianmtr commented on Dockerfile
> +FROM jinaai/jina:2.0.7
we're at 8, I think

2021-07-22 10:30 UTC, alaeddine-13 commented on Dockerfile
> +FROM jinaai/jina:2.0.7
updated

2021-07-22 12:44 UTC, cristianmtr reviewed
great job!

2021-07-22 12:54 UTC, JoanFM requested changes

2021-07-22 12:54 UTC, JoanFM commented on tests/integration/test_exec.py
> +    with Flow.load_config('tests/integration/flow.yml') as f:
please make the `path` relative to the `current` code dir.

2021-07-22 12:54 UTC, JoanFM commented on tests/integration/test_exec.py
> +    assert resp is not None
please assert that the `result` has some good embeddings

2021-07-22 12:54 UTC, JoanFM commented on tests/integration/test_exec.py
> +    with Flow.load_config('tests/integration/flow.yml') as f:
same here for the paths

2021-07-22 12:54 UTC, JoanFM commented on tests/integration/test_exec.py
> +    for doc in responses[0].docs:
assert length of docs before entering in loop

2021-07-22 12:54 UTC, JoanFM commented on tests/unit/test_exec.py
> +    assert all(
can we check what order it is detected instead of a for?

2021-07-22 12:54 UTC, JoanFM commented on tests/unit/test_exec.py
> +    segmenter = YoloV5Segmenter(model_name_or_path='tests/data/models/yolov5m.pt')
make paths relative to cur_dir

2021-07-22 12:54 UTC, JoanFM commented on tests/unit/test_exec.py
> +    segmenter = YoloV5Segmenter(model_name_or_path='tests/data/models/yolov5m.pt',
sanme here and everywhere

2021-07-22 13:18 UTC, alaeddine-13 commented on tests/integration/test_exec.py
> +    assert resp is not None
I think if I do so, it will look exaclty like the test below (`test_chunks_exists`)
Maybe I should just delete it ?

2021-07-22 21:16 UTC, alaeddine-13 commented on tests/integration/test_exec.py
> +    assert resp is not None
I removed it. Asserting the chunks will make the test look similar to `test_chunks_exists` and there's no point in having duplicate tests. If you think there's a need, I can add other tests, otherwise, maybe we can merge

2021-07-23 06:29 UTC, JoanFM requested changes

2021-07-23 06:29 UTC, JoanFM commented on tests/unit/test_exec.py
> +        'https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt'
I think this test depending on a URI should be removed or handled with some sort of mocking. This may easily be removed and connections problems may appear during testing

2021-07-23 06:29 UTC, JoanFM commented on tests/unit/test_exec.py
> +    assert person_chunk.chunks[0].tags["label"] == "person"
please use single quotes

2021-07-23 06:29 UTC, JoanFM commented on yolov5_segmenter.py
> +                        *xyxy, conf, cls = det
instead of having here a list, please apply better names to all of them.
 (left_corner, ..., ..., ... ) , conf, cls = det

I am not sure what best names is but it will be better understood

2021-07-23 06:29 UTC, JoanFM commented on yolov5_segmenter.py
> +                        crop = doc.blob[int(xyxy[1]):int(xyxy[3]), int(xyxy[0]):int(xyxy[2]), :]
Here you have strong assumptions of the shape of the input, is it well documented?

2021-07-23 06:29 UTC, JoanFM commented on yolov5_segmenter.py
> +        self.model = self._attempt_load(self.model_name_or_path)
please, call it simply `_load`. Everything is an attempt

2021-07-23 06:53 UTC, alaeddine-13 commented on yolov5_segmenter.py
> +                        crop = doc.blob[int(xyxy[1]):int(xyxy[3]), int(xyxy[0]):int(xyxy[2]), :]
yes the segmenter always receives an image of shape (height, weight, channels) and the bounding boxes are always inside the input image

2021-07-23 06:58 UTC, alaeddine-13 commented on tests/unit/test_exec.py
> +        'https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt'
done

2021-07-23 06:58 UTC, alaeddine-13 commented on tests/unit/test_exec.py
> +    assert person_chunk.chunks[0].tags["label"] == "person"
done

2021-07-23 06:58 UTC, alaeddine-13 commented on yolov5_segmenter.py
> +                        *xyxy, conf, cls = det
done

2021-07-23 06:58 UTC, alaeddine-13 commented on yolov5_segmenter.py
> +        self.model = self._attempt_load(self.model_name_or_path)
done

2021-07-23 11:30 UTC, JoanFM approved these changes

2021-07-23 11:33 UTC, merged